<?php
namespace App\Traits;

use App\Models\Resource;
use App\Services\ResourceService;

trait HasResources {
    public function resources(){
        return $this->morphMany(Resource::class, 'resourcable');
    }

    public function resource(){
        return $this->morphOne(Resource::class, 'resourcable');
    }

    public function getImageAttribute(){
        if ($this->relationLoaded('resources')){
            return $this->resources->where('type', 'image')->first();
        }

        return $this->resources()->where('type', 'image')->first();
    }

    public function delete()
    {
        if ($this->resources()->exists()) {
            $rs = new ResourceService();
            foreach ($this->resources as $res) {
                $rs->destroy($res);
            }
        }
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
